name: build web

on: 
  push:
    branches: 
      - master
    paths: 
      - web/**
  pull_request:
    branches:
      - master
    paths:
      - web/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: checkout
    - uses: borales/actions-yarn@v2.1.0
      name: Install dependencies
      with:
        cmd: --cwd web install # 指定目录
    - uses: borales/actions-yarn@v2.1.0
      name: Build dist
      with:
        cmd: --cwd web build # 指定目录
    - name: Commit dist
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "[CI]Build web dist" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

